// Layer Declaration header
//
// This file is auto-generated by cmake, don't edit it.

#include "layer/absval.h"
namespace ncnn { DEFINE_LAYER_CREATOR(AbsVal) }
#include "layer/riscv/absval_riscv.h"
namespace ncnn { DEFINE_LAYER_CREATOR(AbsVal_riscv) }
#include "layer/batchnorm.h"
namespace ncnn { DEFINE_LAYER_CREATOR(BatchNorm) }
#include "layer/riscv/batchnorm_riscv.h"
namespace ncnn { DEFINE_LAYER_CREATOR(BatchNorm_riscv) }
#include "layer/bias.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Bias) }
#include "layer/bnll.h"
namespace ncnn { DEFINE_LAYER_CREATOR(BNLL) }
#include "layer/concat.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Concat) }
#include "layer/riscv/concat_riscv.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Concat_riscv) }
#include "layer/convolution.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Convolution) }
#include "layer/riscv/convolution_riscv.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Convolution_riscv) }
#include "layer/crop.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Crop) }
#include "layer/riscv/crop_riscv.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Crop_riscv) }
#include "layer/deconvolution.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Deconvolution) }
#include "layer/riscv/deconvolution_riscv.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Deconvolution_riscv) }
#include "layer/dropout.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Dropout) }
#include "layer/riscv/dropout_riscv.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Dropout_riscv) }
#include "layer/eltwise.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Eltwise) }
#include "layer/elu.h"
namespace ncnn { DEFINE_LAYER_CREATOR(ELU) }
#include "layer/embed.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Embed) }
#include "layer/exp.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Exp) }
#include "layer/flatten.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Flatten) }
#include "layer/riscv/flatten_riscv.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Flatten_riscv) }
#include "layer/innerproduct.h"
namespace ncnn { DEFINE_LAYER_CREATOR(InnerProduct) }
#include "layer/riscv/innerproduct_riscv.h"
namespace ncnn { DEFINE_LAYER_CREATOR(InnerProduct_riscv) }
#include "layer/input.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Input) }
#include "layer/log.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Log) }
#include "layer/lrn.h"
namespace ncnn { DEFINE_LAYER_CREATOR(LRN) }
#include "layer/memorydata.h"
namespace ncnn { DEFINE_LAYER_CREATOR(MemoryData) }
#include "layer/mvn.h"
namespace ncnn { DEFINE_LAYER_CREATOR(MVN) }
#include "layer/pooling.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Pooling) }
#include "layer/riscv/pooling_riscv.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Pooling_riscv) }
#include "layer/power.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Power) }
#include "layer/prelu.h"
namespace ncnn { DEFINE_LAYER_CREATOR(PReLU) }
#include "layer/riscv/prelu_riscv.h"
namespace ncnn { DEFINE_LAYER_CREATOR(PReLU_riscv) }
#include "layer/proposal.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Proposal) }
#include "layer/reduction.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Reduction) }
#include "layer/relu.h"
namespace ncnn { DEFINE_LAYER_CREATOR(ReLU) }
#include "layer/riscv/relu_riscv.h"
namespace ncnn { DEFINE_LAYER_CREATOR(ReLU_riscv) }
#include "layer/reshape.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Reshape) }
#include "layer/roipooling.h"
namespace ncnn { DEFINE_LAYER_CREATOR(ROIPooling) }
#include "layer/scale.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Scale) }
#include "layer/sigmoid.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Sigmoid) }
#include "layer/riscv/sigmoid_riscv.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Sigmoid_riscv) }
#include "layer/slice.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Slice) }
#include "layer/softmax.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Softmax) }
#include "layer/riscv/softmax_riscv.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Softmax_riscv) }
#include "layer/split.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Split) }
#include "layer/tanh.h"
namespace ncnn { DEFINE_LAYER_CREATOR(TanH) }
#include "layer/riscv/tanh_riscv.h"
namespace ncnn { DEFINE_LAYER_CREATOR(TanH_riscv) }
#include "layer/threshold.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Threshold) }
#include "layer/tile.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Tile) }
#include "layer/rnn.h"
namespace ncnn { DEFINE_LAYER_CREATOR(RNN) }
#include "layer/lstm.h"
namespace ncnn { DEFINE_LAYER_CREATOR(LSTM) }
#include "layer/binaryop.h"
namespace ncnn { DEFINE_LAYER_CREATOR(BinaryOp) }
#include "layer/riscv/binaryop_riscv.h"
namespace ncnn { DEFINE_LAYER_CREATOR(BinaryOp_riscv) }
#include "layer/unaryop.h"
namespace ncnn { DEFINE_LAYER_CREATOR(UnaryOp) }
#include "layer/riscv/unaryop_riscv.h"
namespace ncnn { DEFINE_LAYER_CREATOR(UnaryOp_riscv) }
#include "layer/convolutiondepthwise.h"
namespace ncnn { DEFINE_LAYER_CREATOR(ConvolutionDepthWise) }
#include "layer/riscv/convolutiondepthwise_riscv.h"
namespace ncnn { DEFINE_LAYER_CREATOR(ConvolutionDepthWise_riscv) }
#include "layer/padding.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Padding) }
#include "layer/riscv/padding_riscv.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Padding_riscv) }
#include "layer/squeeze.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Squeeze) }
#include "layer/expanddims.h"
namespace ncnn { DEFINE_LAYER_CREATOR(ExpandDims) }
#include "layer/normalize.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Normalize) }
#include "layer/permute.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Permute) }
#include "layer/priorbox.h"
namespace ncnn { DEFINE_LAYER_CREATOR(PriorBox) }
#include "layer/detectionoutput.h"
namespace ncnn { DEFINE_LAYER_CREATOR(DetectionOutput) }
#include "layer/interp.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Interp) }
#include "layer/riscv/interp_riscv.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Interp_riscv) }
#include "layer/deconvolutiondepthwise.h"
namespace ncnn { DEFINE_LAYER_CREATOR(DeconvolutionDepthWise) }
#include "layer/riscv/deconvolutiondepthwise_riscv.h"
namespace ncnn { DEFINE_LAYER_CREATOR(DeconvolutionDepthWise_riscv) }
#include "layer/shufflechannel.h"
namespace ncnn { DEFINE_LAYER_CREATOR(ShuffleChannel) }
#include "layer/instancenorm.h"
namespace ncnn { DEFINE_LAYER_CREATOR(InstanceNorm) }
#include "layer/riscv/instancenorm_riscv.h"
namespace ncnn { DEFINE_LAYER_CREATOR(InstanceNorm_riscv) }
#include "layer/clip.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Clip) }
#include "layer/riscv/clip_riscv.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Clip_riscv) }
#include "layer/reorg.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Reorg) }
#include "layer/yolodetectionoutput.h"
namespace ncnn { DEFINE_LAYER_CREATOR(YoloDetectionOutput) }
#include "layer/quantize.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Quantize) }
#include "layer/dequantize.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Dequantize) }
#include "layer/yolov3detectionoutput.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Yolov3DetectionOutput) }
#include "layer/psroipooling.h"
namespace ncnn { DEFINE_LAYER_CREATOR(PSROIPooling) }
#include "layer/roialign.h"
namespace ncnn { DEFINE_LAYER_CREATOR(ROIAlign) }
#include "layer/packing.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Packing) }
#include "layer/riscv/packing_riscv.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Packing_riscv) }
#include "layer/requantize.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Requantize) }
#include "layer/cast.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Cast) }
#include "layer/riscv/cast_riscv.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Cast_riscv) }
#include "layer/hardsigmoid.h"
namespace ncnn { DEFINE_LAYER_CREATOR(HardSigmoid) }
#include "layer/riscv/hardsigmoid_riscv.h"
namespace ncnn { DEFINE_LAYER_CREATOR(HardSigmoid_riscv) }
#include "layer/selu.h"
namespace ncnn { DEFINE_LAYER_CREATOR(SELU) }
#include "layer/riscv/selu_riscv.h"
namespace ncnn { DEFINE_LAYER_CREATOR(SELU_riscv) }
#include "layer/hardswish.h"
namespace ncnn { DEFINE_LAYER_CREATOR(HardSwish) }
#include "layer/riscv/hardswish_riscv.h"
namespace ncnn { DEFINE_LAYER_CREATOR(HardSwish_riscv) }
#include "layer/noop.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Noop) }
#include "layer/pixelshuffle.h"
namespace ncnn { DEFINE_LAYER_CREATOR(PixelShuffle) }
#include "layer/deepcopy.h"
namespace ncnn { DEFINE_LAYER_CREATOR(DeepCopy) }
#include "layer/mish.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Mish) }
#include "layer/riscv/mish_riscv.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Mish_riscv) }
#include "layer/statisticspooling.h"
namespace ncnn { DEFINE_LAYER_CREATOR(StatisticsPooling) }
#include "layer/swish.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Swish) }
#include "layer/riscv/swish_riscv.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Swish_riscv) }
#include "layer/gemm.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Gemm) }
#include "layer/riscv/gemm_riscv.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Gemm_riscv) }
#include "layer/groupnorm.h"
namespace ncnn { DEFINE_LAYER_CREATOR(GroupNorm) }
#include "layer/layernorm.h"
namespace ncnn { DEFINE_LAYER_CREATOR(LayerNorm) }
#include "layer/softplus.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Softplus) }
#include "layer/gru.h"
namespace ncnn { DEFINE_LAYER_CREATOR(GRU) }
#include "layer/riscv/gru_riscv.h"
namespace ncnn { DEFINE_LAYER_CREATOR(GRU_riscv) }
#include "layer/multiheadattention.h"
namespace ncnn { DEFINE_LAYER_CREATOR(MultiHeadAttention) }
#include "layer/gelu.h"
namespace ncnn { DEFINE_LAYER_CREATOR(GELU) }
#include "layer/riscv/gelu_riscv.h"
namespace ncnn { DEFINE_LAYER_CREATOR(GELU_riscv) }
#include "layer/convolution1d.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Convolution1D) }
#include "layer/riscv/convolution1d_riscv.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Convolution1D_riscv) }
#include "layer/pooling1d.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Pooling1D) }
#include "layer/convolutiondepthwise1d.h"
namespace ncnn { DEFINE_LAYER_CREATOR(ConvolutionDepthWise1D) }
#include "layer/convolution3d.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Convolution3D) }
#include "layer/convolutiondepthwise3d.h"
namespace ncnn { DEFINE_LAYER_CREATOR(ConvolutionDepthWise3D) }
#include "layer/pooling3d.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Pooling3D) }
#include "layer/matmul.h"
namespace ncnn { DEFINE_LAYER_CREATOR(MatMul) }
#include "layer/deconvolution1d.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Deconvolution1D) }
#include "layer/deconvolutiondepthwise1d.h"
namespace ncnn { DEFINE_LAYER_CREATOR(DeconvolutionDepthWise1D) }
#include "layer/deconvolution3d.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Deconvolution3D) }
#include "layer/deconvolutiondepthwise3d.h"
namespace ncnn { DEFINE_LAYER_CREATOR(DeconvolutionDepthWise3D) }
#include "layer/einsum.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Einsum) }
#include "layer/deformableconv2d.h"
namespace ncnn { DEFINE_LAYER_CREATOR(DeformableConv2D) }
#include "layer/glu.h"
namespace ncnn { DEFINE_LAYER_CREATOR(GLU) }
#include "layer/fold.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Fold) }
#include "layer/unfold.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Unfold) }
#include "layer/gridsample.h"
namespace ncnn { DEFINE_LAYER_CREATOR(GridSample) }
#include "layer/cumulativesum.h"
namespace ncnn { DEFINE_LAYER_CREATOR(CumulativeSum) }
#include "layer/copyto.h"
namespace ncnn { DEFINE_LAYER_CREATOR(CopyTo) }
#include "layer/erf.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Erf) }
#include "layer/diag.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Diag) }
#include "layer/celu.h"
namespace ncnn { DEFINE_LAYER_CREATOR(CELU) }
#include "layer/shrink.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Shrink) }

